-- =========================================================
-- Nihongo — Beginner lessons seed (generated)
-- Generated by scripts/generate_beginner_seed.mjs — DO NOT EDIT.
-- Source: data/beginner-lessons.json (130 cards)
--
-- Adds ONE flat level "Beginner" to the "vocabulary" module
-- mixing all four card types from the JSON. No group_name —
-- same rank as Verbs / Adjectives.
--
-- Idempotent:
--   * Level insert guarded on (module_id, name).
--   * Card inserts only fire when the level currently holds zero
--     cards, so re-runs don't produce duplicates.
--
-- Types:
--     21  adjective_flashcard
--      3  adverb_flashcard
--     81  noun_flashcard
--     25  verb_flashcard
-- =========================================================

with m as (select id from modules where slug = 'vocabulary')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Beginner', 5, 'both' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Beginner'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'vocabulary' and lv.name = 'Beginner'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, v.fields
from do_seed ds
cross join (values
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"思う (おもう)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"思います","potential_form":"—","translation_en":"to think"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"開く (あく)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"開きます","potential_form":"—","translation_en":"to open (intransitive)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"閉まる (しまる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"閉まります","potential_form":"—","translation_en":"to close (intransitive)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"つく","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"つきます","potential_form":"—","translation_en":"to come on, to be switched on (light)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"貸す (かす)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"貸します","potential_form":"—","translation_en":"to lend"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"返す (かえす)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"返します","potential_form":"—","translation_en":"to give back, to return (something)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"消える (きえる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"消えます","potential_form":"—","translation_en":"to go out, to disappear"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"決める (きめる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"決めます","potential_form":"—","translation_en":"to decide"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"見える (みえる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"見えます","potential_form":"—","translation_en":"to be visible, can be seen"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"聞こえる (きこえる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"聞こえます","potential_form":"—","translation_en":"to be audible, can be heard"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"借りる (かりる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"借ります","potential_form":"—","translation_en":"to borrow"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"使う (つかう)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"使います","potential_form":"—","translation_en":"to use"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"おごる","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"おごります","potential_form":"—","translation_en":"to treat (pay for someone)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"酔っ払う (よっぱらう)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"酔っ払います","potential_form":"—","translation_en":"to get drunk"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"運ぶ (はこぶ)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"運びます","potential_form":"—","translation_en":"to carry, to transport"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"払う (はらう)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"払います","potential_form":"—","translation_en":"to pay"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"遊ぶ (あそぶ)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"遊びます","potential_form":"—","translation_en":"to play, to hang out"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"歌う (うたう)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"歌います","potential_form":"—","translation_en":"to sing"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"曲がる (まがる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"曲がります","potential_form":"—","translation_en":"to turn (a corner)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"通る (とおる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"通ります","potential_form":"—","translation_en":"to pass through, to go along"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"走る (はしる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"走ります","potential_form":"—","translation_en":"to run"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"飛ぶ (とぶ)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"飛びます","potential_form":"—","translation_en":"to fly"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"渡る (わたる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"渡ります","potential_form":"—","translation_en":"to cross (a bridge, a street)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"曲げる (まげる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"曲げます","potential_form":"—","translation_en":"to bend (something)"}'::jsonb),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"流れる (ながれる)","te_form":"—","ta_form":"—","nai_form":"—","masu_form":"流れます","potential_form":"—","translation_en":"to flow"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"忙しい","hiragana":"いそがしい","short_form":"忙しい","long_form":"忙しいです","definition_en":"busy","opposite":"","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"悲しい","hiragana":"かなしい","short_form":"悲しい","long_form":"悲しいです","definition_en":"sad","opposite":"","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"嬉しい","hiragana":"うれしい","short_form":"嬉しい","long_form":"嬉しいです","definition_en":"glad, happy","opposite":"","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"楽しい","hiragana":"たのしい","short_form":"楽しい","long_form":"楽しいです","definition_en":"fun, enjoyable","opposite":"","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"寂しい","hiragana":"さびしい","short_form":"寂しい","long_form":"寂しいです","definition_en":"lonely","opposite":"","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"痛い","hiragana":"いたい","short_form":"痛い","long_form":"痛いです","definition_en":"painful, sore","opposite":"","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"高い","hiragana":"たかい","short_form":"高い","long_form":"高いです","definition_en":"high, tall; expensive","opposite":"低い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"低い","hiragana":"ひくい","short_form":"低い","long_form":"低いです","definition_en":"low","opposite":"高い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"近い","hiragana":"ちかい","short_form":"近い","long_form":"近いです","definition_en":"near, close","opposite":"遠い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"遠い","hiragana":"とおい","short_form":"遠い","long_form":"遠いです","definition_en":"far","opposite":"近い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"明るい","hiragana":"あかるい","short_form":"明るい","long_form":"明るいです","definition_en":"bright","opposite":"暗い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"暗い","hiragana":"くらい","short_form":"暗い","long_form":"暗いです","definition_en":"dark","opposite":"明るい","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"広い","hiragana":"ひろい","short_form":"広い","long_form":"広いです","definition_en":"spacious, wide","opposite":"狭い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"狭い","hiragana":"せまい","short_form":"狭い","long_form":"狭いです","definition_en":"narrow, cramped","opposite":"広い","adjective_class":"i"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"暇","hiragana":"ひま","short_form":"暇だ","long_form":"暇です","definition_en":"free (not busy)","opposite":"","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"大変","hiragana":"たいへん","short_form":"大変だ","long_form":"大変です","definition_en":"tough, hard going","opposite":"","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"便利","hiragana":"べんり","short_form":"便利だ","long_form":"便利です","definition_en":"convenient","opposite":"不便","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"不便","hiragana":"ふべん","short_form":"不便だ","long_form":"不便です","definition_en":"inconvenient","opposite":"便利","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"立派","hiragana":"りっぱ","short_form":"立派だ","long_form":"立派です","definition_en":"splendid, impressive","opposite":"","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"親切","hiragana":"しんせつ","short_form":"親切だ","long_form":"親切です","definition_en":"kind, helpful","opposite":"","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adjective_flashcard","kanji":"同じ","hiragana":"おなじ","short_form":"同じだ","long_form":"同じです","definition_en":"same","opposite":"","adjective_class":"na"}'::jsonb),
  ('{"card_type":"adverb_flashcard","japanese":"","hiragana":"ぴったり","english":"exactly, perfectly (fitting)"}'::jsonb),
  ('{"card_type":"adverb_flashcard","japanese":"","hiragana":"まっすぐ","english":"straight ahead"}'::jsonb),
  ('{"card_type":"adverb_flashcard","japanese":"","hiragana":"いつか","english":"someday, sometime"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"今度","hiragana":"こんど","english":"next time, soon"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"保育園","hiragana":"ほいくえん","english":"nursery, daycare"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"保育園児","hiragana":"ほいくえんじ","english":"nursery child"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"幼稚園","hiragana":"ようちえん","english":"kindergarten"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"幼稚園児","hiragana":"ようちえんじ","english":"kindergarten child"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"小学校","hiragana":"しょうがっこう","english":"primary school"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"小学生","hiragana":"しょうがくせい","english":"primary school pupil"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"中学校","hiragana":"ちゅうがっこう","english":"junior high school"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"中学生","hiragana":"ちゅうがくせい","english":"junior high student"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"高校","hiragana":"こうこう","english":"high school"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"高校生","hiragana":"こうこうせい","english":"high school student"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"大学","hiragana":"だいがく","english":"university"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"大学生","hiragana":"だいがくせい","english":"university student"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"大学院","hiragana":"だいがくいん","english":"graduate school"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"大学院生","hiragana":"だいがくいんせい","english":"graduate student"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"予備校","hiragana":"よびこう","english":"cram school (exam prep)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"予備校生","hiragana":"よびこうせい","english":"cram school student"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"音","hiragana":"おと","english":"sound, noise"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"音楽","hiragana":"おんがく","english":"music"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"声","hiragana":"こえ","english":"voice"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"鳴き声","hiragana":"なきごえ","english":"animal cry, call"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"形","hiragana":"かたち","english":"shape, form"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"〜階建て","hiragana":"かいだて","english":"-storey (building)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"〜階","hiragana":"かい","english":"floor, storey"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"アパート","english":"apartment (low-rise)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"マンション","english":"apartment building, condo"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"地下","hiragana":"ちか","english":"basement, underground"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"屋上","hiragana":"おくじょう","english":"rooftop"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"階段","hiragana":"かいだん","english":"stairs"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"非常口","hiragana":"ひじょうぐち","english":"emergency exit"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"建物","hiragana":"たてもの","english":"building"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"柄","hiragana":"がら","english":"pattern (on fabric)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"値段","hiragana":"ねだん","english":"price"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"サイズ","english":"size"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"ひげ","english":"beard, moustache"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"お客さん","hiragana":"おきゃくさん","english":"customer, guest"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"酔っ払い","hiragana":"よっぱらい","english":"drunk person"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"メニュー","english":"menu"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"生ビール","hiragana":"なまビール","english":"draft beer"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"大ジョッキ","hiragana":"だいジョッキ","english":"large beer mug"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"中ジョッキ","hiragana":"ちゅうジョッキ","english":"medium beer mug"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"お座敷","hiragana":"おざしき","english":"tatami room (in a restaurant)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"座蒲団","hiragana":"ざぶとん","english":"floor cushion"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"畳","hiragana":"たたみ","english":"tatami mat"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"伝票","hiragana":"でんぴょう","english":"bill, check (restaurant slip)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"レジ","english":"cash register, checkout"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"レシート","english":"receipt"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"領収書","hiragana":"りょうしゅうしょ","english":"formal receipt"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"音楽会","hiragana":"おんがくかい","english":"concert"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"歌","hiragana":"うた","english":"song"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"ピアノ","english":"piano"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"近所","hiragana":"きんじょ","english":"neighbourhood"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"近く","hiragana":"ちかく","english":"nearby, vicinity"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"遠く","hiragana":"とおく","english":"far away, distance"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"化粧室","hiragana":"けしょうしつ","english":"restroom"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"女性用","hiragana":"じょせいよう","english":"for women"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"男性用","hiragana":"だんせいよう","english":"for men"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"大人用","hiragana":"おとなよう","english":"for adults"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"子供用","hiragana":"こどもよう","english":"for children"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"エレベーター","english":"elevator"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"エスカレーター","english":"escalator"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"角","hiragana":"かど","english":"corner (street)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"隅","hiragana":"すみ","english":"corner (inside a room)"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"正面","hiragana":"しょうめん","english":"front, facade"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"突き当り","hiragana":"つきあたり","english":"end of a corridor or street"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"真ん中","hiragana":"まんなか","english":"middle, centre"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"間","hiragana":"あいだ","english":"between, interval"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"先","hiragana":"さき","english":"ahead, further on"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"手前","hiragana":"てまえ","english":"this side, just before"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"向こう","hiragana":"むこう","english":"the other side, over there"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"まわり","english":"surroundings, around"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"","hiragana":"ななめ","english":"diagonal, at an angle"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"鳥","hiragana":"とり","english":"bird"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"空","hiragana":"そら","english":"sky"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"町","hiragana":"まち","english":"town"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"廊下","hiragana":"ろうか","english":"corridor, hallway"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"橋","hiragana":"はし","english":"bridge"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"海","hiragana":"うみ","english":"sea"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"山","hiragana":"やま","english":"mountain"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"川","hiragana":"かわ","english":"river"}'::jsonb),
  ('{"card_type":"noun_flashcard","japanese":"観光地","hiragana":"かんこうち","english":"tourist spot"}'::jsonb)
) as v(fields);

-- Sanity check
select lv.name, count(c.id) as cards
from module_levels lv
join modules m on m.id = lv.module_id
left join cards c on c.level_id = lv.id
where m.slug = 'vocabulary' and lv.name = 'Beginner'
group by lv.name;
