-- =========================================================
-- Nihongo — Verbs flashcards seed
-- Generated by scripts/generate_verbs_seed.mjs from
--   supabase/data/verbs.json (83 verbs total).
-- Adds two levels to the "vocabulary" module and seeds them.
-- Idempotent: re-running is a no-op once the levels are populated.
-- =========================================================

-- ─── Level: Verbs — SNG List (65 cards) ─────────────────────
with m as (select id from modules where slug = 'vocabulary')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Verbs — SNG List', 100, 'none' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Verbs — SNG List'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'vocabulary' and lv.name = 'Verbs — SNG List'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, fld::jsonb from do_seed ds
cross join (values
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"会う (あう)","te_form":"会って","ta_form":"会った","nai_form":"会わない","masu_form":"会います","potential_form":"会えます","translation_en":"to meet"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"開ける (あける)","te_form":"開けて","ta_form":"開けた","nai_form":"開けない","masu_form":"開けます","potential_form":"開けられます","translation_en":"to open"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"ある","te_form":"あって","ta_form":"あった","nai_form":"ない","masu_form":"あります","potential_form":"—","translation_en":"to exist / to have (inanimate)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"歩く (あるく)","te_form":"歩いて","ta_form":"歩いた","nai_form":"歩かない","masu_form":"歩きます","potential_form":"歩けます","translation_en":"to walk"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"言う (いう)","te_form":"言って","ta_form":"言った","nai_form":"言わない","masu_form":"言います","potential_form":"言えます","translation_en":"to say"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"行く (いく)","te_form":"行って","ta_form":"行った","nai_form":"行かない","masu_form":"行きます","potential_form":"行けます","translation_en":"to go"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"いる","te_form":"いて","ta_form":"いた","nai_form":"いない","masu_form":"います","potential_form":"いられます","translation_en":"to exist / to be (animate)"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"入れる (いれる)","te_form":"入れて","ta_form":"入れた","nai_form":"入れない","masu_form":"入れます","potential_form":"入れられます","translation_en":"to put in / insert"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"要る (いる)","te_form":"—","ta_form":"—","nai_form":"要らない","masu_form":"要ります","potential_form":"—","translation_en":"to need"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"売る (うる)","te_form":"売って","ta_form":"売った","nai_form":"売らない","masu_form":"売ります","potential_form":"売れます","translation_en":"to sell"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"選ぶ (えらぶ)","te_form":"選んで","ta_form":"選んだ","nai_form":"選ばない","masu_form":"選びます","potential_form":"選べます","translation_en":"to choose"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"起きる (おきる)","te_form":"起きて","ta_form":"起きた","nai_form":"起きない","masu_form":"起きます","potential_form":"起きられます","translation_en":"to wake up / get up"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"置く (おく)","te_form":"置いて","ta_form":"置いた","nai_form":"置かない","masu_form":"置きます","potential_form":"置けます","translation_en":"to put / place"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"遅れる (おくれる)","te_form":"遅れて","ta_form":"遅れた","nai_form":"遅れない","masu_form":"遅れます","potential_form":"遅れられます","translation_en":"to be late"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"泳ぐ (およぐ)","te_form":"泳いで","ta_form":"泳いだ","nai_form":"泳がない","masu_form":"泳ぎます","potential_form":"泳げます","translation_en":"to swim"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"降りる (おりる)","te_form":"降りて","ta_form":"降りた","nai_form":"降りない","masu_form":"降ります","potential_form":"降りられます","translation_en":"to get off / descend"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"教える (おしえる)","te_form":"教えて","ta_form":"教えた","nai_form":"教えない","masu_form":"教えます","potential_form":"教えられます","translation_en":"to teach / tell"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"買う (かう)","te_form":"買って","ta_form":"買った","nai_form":"買わない","masu_form":"買います","potential_form":"買えます","translation_en":"to buy"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"帰る (かえる)","te_form":"帰って","ta_form":"帰った","nai_form":"帰らない","masu_form":"帰ります","potential_form":"帰れます","translation_en":"to return home"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"かかる","te_form":"かかって","ta_form":"かかった","nai_form":"かからない","masu_form":"かかります","potential_form":"—","translation_en":"to take (time/money)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"書く (かく)","te_form":"書いて","ta_form":"書いた","nai_form":"書かない","masu_form":"書きます","potential_form":"書けます","translation_en":"to write"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"かける","te_form":"かけて","ta_form":"かけた","nai_form":"かけない","masu_form":"かけます","potential_form":"かけられます","translation_en":"to hang / make (a phone call) / wear (glasses)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"頑張る (がんばる)","te_form":"頑張って","ta_form":"頑張った","nai_form":"頑張らない","masu_form":"頑張ります","potential_form":"頑張れます","translation_en":"to do one''s best"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"聞く (きく)","te_form":"聞いて","ta_form":"聞いた","nai_form":"聞かない","masu_form":"聞きます","potential_form":"聞けます","translation_en":"to listen / hear / ask"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"着る (きる)","te_form":"着て","ta_form":"着た","nai_form":"着ない","masu_form":"着ます","potential_form":"着られます","translation_en":"to wear (upper body)"}'),
  ('{"card_type":"verb_flashcard","group":"III","dictionary_form":"来る (くる)","te_form":"来て","ta_form":"来た","nai_form":"来ない","masu_form":"来ます","potential_form":"来られます","translation_en":"to come"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"切る (きる)","te_form":"切って","ta_form":"切った","nai_form":"切らない","masu_form":"切ります","potential_form":"切れます","translation_en":"to cut"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"消す (けす)","te_form":"消して","ta_form":"消した","nai_form":"消さない","masu_form":"消します","potential_form":"消せます","translation_en":"to turn off / erase"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"答える (こたえる)","te_form":"答えて","ta_form":"答えた","nai_form":"答えない","masu_form":"答えます","potential_form":"答えられます","translation_en":"to answer"}'),
  ('{"card_type":"verb_flashcard","group":"III","dictionary_form":"する","te_form":"して","ta_form":"した","nai_form":"しない","masu_form":"します","potential_form":"できます","translation_en":"to do"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"閉める (しめる)","te_form":"閉めて","ta_form":"閉めた","nai_form":"閉めない","masu_form":"閉めます","potential_form":"閉められます","translation_en":"to close"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"知る (しる)","te_form":"知って","ta_form":"知った","nai_form":"知らない","masu_form":"知っています","potential_form":"分かりま す (can know/understand)","translation_en":"to know"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"吸う (すう)","te_form":"吸って","ta_form":"吸った","nai_form":"吸わない","masu_form":"吸います","potential_form":"吸えます","translation_en":"to smoke / inhale"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"住む (すむ)","te_form":"住んで","ta_form":"住んだ","nai_form":"住まない","masu_form":"住みます","potential_form":"住めます","translation_en":"to live / reside"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"座る (すわる)","te_form":"座って","ta_form":"座った","nai_form":"座らない","masu_form":"座ります","potential_form":"座れます","translation_en":"to sit"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"出す (だす)","te_form":"出して","ta_form":"出した","nai_form":"出さない","masu_form":"だします","potential_form":"出せます","translation_en":"to take out / submit"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"立つ (たつ)","te_form":"立って","ta_form":"立った","nai_form":"立たない","masu_form":"立ちます","potential_form":"立てます","translation_en":"to stand"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"食べる (たべる)","te_form":"食べて","ta_form":"食べた","nai_form":"食べない","masu_form":"食べます","potential_form":"食べられます","translation_en":"to eat"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"違う (ちがう)","te_form":"違って","ta_form":"違った","nai_form":"違わない","masu_form":"違います","potential_form":"—","translation_en":"to differ / be wrong"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"作る (つくる)","te_form":"作って","ta_form":"作った","nai_form":"作らない","masu_form":"作ります","potential_form":"作れます","translation_en":"to make"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"つける","te_form":"つけて","ta_form":"つけた","nai_form":"つけない","masu_form":"つけます","potential_form":"つけられます","translation_en":"to turn on / attach"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"勤める (つとめる)","te_form":"勤めて","ta_form":"勤めた","nai_form":"勤めない","masu_form":"勤めます","potential_form":"勤められます","translation_en":"to work for / be employed"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"出る (でる)","te_form":"出て","ta_form":"出た","nai_form":"出ない","masu_form":"出ます","potential_form":"出られます","translation_en":"to leave / go out / exit"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"できる","te_form":"できて","ta_form":"できた","nai_form":"できない","masu_form":"できます","potential_form":"☆できます","translation_en":"to be able to do"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"撮る (とる)","te_form":"撮って","ta_form":"撮った","nai_form":"撮らない","masu_form":"撮ります","potential_form":"撮れます","translation_en":"to take (a photo)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"脱ぐ (ぬぐ)","te_form":"脱いで","ta_form":"脱いだ","nai_form":"脱がない","masu_form":"脱ぎます","potential_form":"脱げます","translation_en":"to take off (clothes)"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"寝る (ねる)","te_form":"寝て","ta_form":"寝た","nai_form":"寝ない","masu_form":"寝ます","potential_form":"寝られます","translation_en":"to sleep"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"飲む (のむ)","te_form":"飲んで","ta_form":"飲んだ","nai_form":"飲まない","masu_form":"飲みます","potential_form":"飲めます","translation_en":"to drink"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"乗る (のる)","te_form":"乗って","ta_form":"乗った","nai_form":"乗らない","masu_form":"乗ります","potential_form":"乗れます","translation_en":"to ride / board"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"乗り換える (のりかえる)","te_form":"乗り換えて","ta_form":"乗り換えた","nai_form":"乗り換えない","masu_form":"乗り換えます","potential_form":"乗り換えられます","translation_en":"to transfer (train/bus)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"履く (はく)","te_form":"履いて","ta_form":"履いた","nai_form":"履かない","masu_form":"履きます","potential_form":"履けます","translation_en":"to wear (shoes, pants, lower body)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"話す (はなす)","te_form":"話して","ta_form":"話した","nai_form":"話さない","masu_form":"話します","potential_form":"話せます","translation_en":"to speak / talk"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"入る (はいる)","te_form":"入って","ta_form":"入った","nai_form":"入らない","masu_form":"入ります","potential_form":"入れます","translation_en":"to enter"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"降る (ふる)","te_form":"降って","ta_form":"降った","nai_form":"降らない","masu_form":"降ります","potential_form":"—","translation_en":"to rain / snow"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"間違える (まちがえる)","te_form":"間違えて","ta_form":"間違えた","nai_form":"間違えない","masu_form":"間違えます","potential_form":"間違えられます","translation_en":"to make a mistake"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"待つ (まつ)","te_form":"待って","ta_form":"待った","nai_form":"待たない","masu_form":"待ちます","potential_form":"待てます","translation_en":"to wait"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"間に合う (まにあう)","te_form":"間に合って","ta_form":"間に合った","nai_form":"間に合わない","masu_form":"間に合います","potential_form":"☆間に合います","translation_en":"to be on time"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"見せる (みせる)","te_form":"見せて","ta_form":"見せた","nai_form":"見せない","masu_form":"見せます","potential_form":"見せられます","translation_en":"to show"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"見る (みる)","te_form":"見て","ta_form":"見た","nai_form":"見ない","masu_form":"見ます","potential_form":"見られます","translation_en":"to see / watch"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"持つ (もつ)","te_form":"持って","ta_form":"持った","nai_form":"持たない","masu_form":"持ちます","potential_form":"持てます","translation_en":"to hold / carry / possess"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"休む (やすむ)","te_form":"休んで","ta_form":"休んだ","nai_form":"休まない","masu_form":"休みます","potential_form":"休めます","translation_en":"to rest / take a day off"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"呼ぶ (よぶ)","te_form":"呼んで","ta_form":"呼んだ","nai_form":"呼ばない","masu_form":"呼びます","potential_form":"呼べます","translation_en":"to call / invite"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"読む (よむ)","te_form":"読んで","ta_form":"読んだ","nai_form":"読まない","masu_form":"読みます","potential_form":"読めます","translation_en":"to read"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"寄る (よる)","te_form":"寄って","ta_form":"寄った","nai_form":"寄らない","masu_form":"寄ります","potential_form":"寄れます","translation_en":"to stop by / drop in"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"分かる (わかる)","te_form":"分かって","ta_form":"分かった","nai_form":"分からない","masu_form":"分かります","potential_form":"☆分かります","translation_en":"to understand"}')
) as v(fld);

-- ─── Level: Verbs — Extra (18 cards) ─────────────────────
with m as (select id from modules where slug = 'vocabulary')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Verbs — Extra', 101, 'none' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Verbs — Extra'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'vocabulary' and lv.name = 'Verbs — Extra'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, fld::jsonb from do_seed ds
cross join (values
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"習う (ならう)","te_form":"習って","ta_form":"習った","nai_form":"習わない","masu_form":"習います","potential_form":"習えます","translation_en":"to learn"}'),
  ('{"card_type":"verb_flashcard","group":"III","dictionary_form":"勉強する (べんきょうする)","te_form":"勉強して","ta_form":"勉強した","nai_form":"勉強しない","masu_form":"勉強します","potential_form":"勉強できます","translation_en":"to study"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"覚える (おぼえる)","te_form":"覚えて","ta_form":"覚えた","nai_form":"覚えない","masu_form":"覚えます","potential_form":"覚えられます","translation_en":"to memorize / remember"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"洗う (あらう)","te_form":"洗って","ta_form":"洗った","nai_form":"洗わない","masu_form":"洗います","potential_form":"洗えます","translation_en":"to wash"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"浴びる (あびる)","te_form":"浴びて","ta_form":"浴びた","nai_form":"浴びない","masu_form":"浴びます","potential_form":"浴びられます","translation_en":"to take (a shower) / bathe"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"磨く (みがく)","te_form":"磨いて","ta_form":"磨いた","nai_form":"磨かない","masu_form":"磨きます","potential_form":"磨けます","translation_en":"to brush / polish"}'),
  ('{"card_type":"verb_flashcard","group":"III","dictionary_form":"散歩する (さんぽする)","te_form":"散歩して","ta_form":"散歩した","nai_form":"散歩しない","masu_form":"散歩します","potential_form":"散歩できます","translation_en":"to take a walk"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"走る (はしる)","te_form":"走って","ta_form":"走った","nai_form":"走らない","masu_form":"走ります","potential_form":"走れます","translation_en":"to run (Note: Group I exception)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"貸す (かす)","te_form":"貸して","ta_form":"貸した","nai_form":"貸さない","masu_form":"貸します","potential_form":"貸せます","translation_en":"to lend"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"借りる (かりる)","te_form":"借りて","ta_form":"借りた","nai_form":"借りない","masu_form":"借ります","potential_form":"借りられます","translation_en":"to borrow"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"あげる","te_form":"あげて","ta_form":"あげた","nai_form":"あげない","masu_form":"あげます","potential_form":"あげられます","translation_en":"to give"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"くれる","te_form":"くれて","ta_form":"くれた","nai_form":"くれない","masu_form":"くれます","potential_form":"くれられます","translation_en":"to give (to me)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"もらう","te_form":"もらって","ta_form":"もらった","nai_form":"もらわない","masu_form":"もらいます","potential_form":"もらえます","translation_en":"to receive"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"並ぶ (ならぶ)","te_form":"並んで","ta_form":"並んだ","nai_form":"並ばない","masu_form":"並びます","potential_form":"並べます","translation_en":"to line up / stand in line"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"並べる (ならべる)","te_form":"並べて","ta_form":"並べた","nai_form":"並べない","masu_form":"並べます","potential_form":"並べられます","translation_en":"to line up / arrange (something)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"吹く (ふく)","te_form":"吹いて","ta_form":"吹いた","nai_form":"吹かない","masu_form":"吹きます","potential_form":"吹けます","translation_en":"to blow (wind)"}'),
  ('{"card_type":"verb_flashcard","group":"I","dictionary_form":"鳴く (なく)","te_form":"鳴いて","ta_form":"鳴いた","nai_form":"鳴かない","masu_form":"鳴きます","potential_form":"鳴けます","translation_en":"to bark / chirp / roar (animal noises)"}'),
  ('{"card_type":"verb_flashcard","group":"II","dictionary_form":"生まれる (うまれる)","te_form":"生まれて","ta_form":"生まれた","nai_form":"生まれない","masu_form":"生まれます","potential_form":"生まれられます","translation_en":"to be born"}')
) as v(fld);

-- Sanity check
select lv.order_index, lv.name, count(c.id) as cards
from module_levels lv
join modules m on m.id = lv.module_id
left join cards c on c.level_id = lv.id
where m.slug = 'vocabulary'
  and lv.name in ('Verbs — SNG List', 'Verbs — Extra')
group by lv.order_index, lv.name
order by lv.order_index;
