-- =========================================================
-- Nihongo — Conjugation flashcard seed (generated)
-- Generated by scripts/generate_conjugation_seed.mjs — DO NOT EDIT.
-- Source: supabase/data/verbs_conjugation.json  (34 entries)
--
-- Adds ONE level to the existing "conjugation" module named
-- "Verb Conjugation Reference" that mixes all three verb groups (I / II / III).
-- Group info stays on each card (`fields.group`) and surfaces as
-- a small pill on the flashcard front.
--
-- The existing conjugation drill levels (typing exercises) are
-- untouched — the "insert if level empty" guard would refuse to
-- add cards to a populated level anyway.
--
-- Idempotent — safe to re-run.
--   * Legacy cleanup: drops the three per-group levels from an
--     earlier attempt (no-op if they never existed).
--   * Level: insert only when a level with the same name is missing.
--   * Cards: insert only when the level currently holds zero cards.
-- =========================================================

-- =========================================================
-- Defensive cleanup — an earlier version of this seed created
-- three separate levels (Group I / II / III). If any of those
-- rows still exist, drop them so we don't ship two flavours of
-- the same content. Safe no-op if they were never created.
-- =========================================================
delete from module_levels
 where module_id = (select id from modules where slug = 'conjugation')
   and name in ('Group I — Godan Verbs', 'Group II — Ichidan Verbs', 'Group III — Irregular Verbs');

-- =========================================================
-- LEVEL 100 — Verb Conjugation Reference (34 verbs, all groups mixed)
-- =========================================================
with m as (select id from modules where slug = 'conjugation')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Verb Conjugation Reference', 100, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Verb Conjugation Reference'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'conjugation' and lv.name = 'Verb Conjugation Reference'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, v.fields
from do_seed ds
cross join (values
  ('{"card_type":"verb_conjugation","group":"I","kanji":"会う","reading":"あう","english":"to meet","ending_note":"u","short":{"present_aff":"あう","present_neg":"あわない","past_aff":"あった","past_neg":"あわなかった","te":"あって","tai":"あいたい","potential":"あえる"},"long":{"present_aff":"あいます","present_neg":"あいません","past_aff":"あいました","past_neg":"あいませんでした","te":"あって","tai":"あいたいです","potential":"あえます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"買う","reading":"かう","english":"to buy","ending_note":"u","short":{"present_aff":"かう","present_neg":"かわない","past_aff":"かった","past_neg":"かわなかった","te":"かって","tai":"かいたい","potential":"かえる"},"long":{"present_aff":"かいます","present_neg":"かいません","past_aff":"かいました","past_neg":"かいませんでした","te":"かって","tai":"かいたいです","potential":"かえます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"待つ","reading":"まつ","english":"to wait","ending_note":"tsu","short":{"present_aff":"まつ","present_neg":"またない","past_aff":"まった","past_neg":"またなかった","te":"まって","tai":"まちたい","potential":"まてる"},"long":{"present_aff":"まちます","present_neg":"まちません","past_aff":"まちました","past_neg":"まちませんでした","te":"まって","tai":"まちたいです","potential":"まてます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"立つ","reading":"たつ","english":"to stand","ending_note":"tsu","short":{"present_aff":"たつ","present_neg":"たたない","past_aff":"たった","past_neg":"たたなかった","te":"たって","tai":"たちたい","potential":"たてる"},"long":{"present_aff":"たちます","present_neg":"たちません","past_aff":"たちました","past_neg":"たちませんでした","te":"たって","tai":"たちたいです","potential":"たてます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"取る","reading":"とる","english":"to take","ending_note":"ru→godan","short":{"present_aff":"とる","present_neg":"とらない","past_aff":"とった","past_neg":"とらなかった","te":"とって","tai":"とりたい","potential":"とれる"},"long":{"present_aff":"とります","present_neg":"とりません","past_aff":"とりました","past_neg":"とりませんでした","te":"とって","tai":"とりたいです","potential":"とれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"飲む","reading":"のむ","english":"to drink","ending_note":"mu","short":{"present_aff":"のむ","present_neg":"のまない","past_aff":"のんだ","past_neg":"のまなかった","te":"のんで","tai":"のみたい","potential":"のめる"},"long":{"present_aff":"のみます","present_neg":"のみません","past_aff":"のみました","past_neg":"のみませんでした","te":"のんで","tai":"のみたいです","potential":"のめます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"読む","reading":"よむ","english":"to read","ending_note":"mu","short":{"present_aff":"よむ","present_neg":"よまない","past_aff":"よんだ","past_neg":"よまなかった","te":"よんで","tai":"よみたい","potential":"よめる"},"long":{"present_aff":"よみます","present_neg":"よみません","past_aff":"よみました","past_neg":"よみませんでした","te":"よんで","tai":"よみたいです","potential":"よめます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"死ぬ","reading":"しぬ","english":"to die","ending_note":"nu","short":{"present_aff":"しぬ","present_neg":"しなない","past_aff":"しんだ","past_neg":"しななかった","te":"しんで","tai":"しにたい","potential":"しねる"},"long":{"present_aff":"しにます","present_neg":"しにません","past_aff":"しにました","past_neg":"しにませんでした","te":"しんで","tai":"しにたいです","potential":"しねます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"書く","reading":"かく","english":"to write","ending_note":"ku","short":{"present_aff":"かく","present_neg":"かかない","past_aff":"かいた","past_neg":"かかなかった","te":"かいて","tai":"かきたい","potential":"かける"},"long":{"present_aff":"かきます","present_neg":"かきません","past_aff":"かきました","past_neg":"かきませんでした","te":"かいて","tai":"かきたいです","potential":"かけます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"聞く","reading":"きく","english":"to listen / to ask","ending_note":"ku","short":{"present_aff":"きく","present_neg":"きかない","past_aff":"きいた","past_neg":"きかなかった","te":"きいて","tai":"ききたい","potential":"きける"},"long":{"present_aff":"ききます","present_neg":"ききません","past_aff":"ききました","past_neg":"ききませんでした","te":"きいて","tai":"ききたいです","potential":"きけます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"行く","reading":"いく","english":"to go","ending_note":"ku (irregular te-form)","short":{"present_aff":"いく","present_neg":"いかない","past_aff":"いった","past_neg":"いかなかった","te":"いって","tai":"いきたい","potential":"いける"},"long":{"present_aff":"いきます","present_neg":"いきません","past_aff":"いきました","past_neg":"いきませんでした","te":"いって","tai":"いきたいです","potential":"いけます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"泳ぐ","reading":"およぐ","english":"to swim","ending_note":"gu","short":{"present_aff":"およぐ","present_neg":"およがない","past_aff":"およいだ","past_neg":"およがなかった","te":"およいで","tai":"およぎたい","potential":"およげる"},"long":{"present_aff":"およぎます","present_neg":"およぎません","past_aff":"およぎました","past_neg":"およぎませんでした","te":"およいで","tai":"およぎたいです","potential":"およげます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"急ぐ","reading":"いそぐ","english":"to hurry","ending_note":"gu","short":{"present_aff":"いそぐ","present_neg":"いそがない","past_aff":"いそいだ","past_neg":"いそがなかった","te":"いそいで","tai":"いそぎたい","potential":"いそげる"},"long":{"present_aff":"いそぎます","present_neg":"いそぎません","past_aff":"いそぎました","past_neg":"いそぎませんでした","te":"いそいで","tai":"いそぎたいです","potential":"いそげます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"話す","reading":"はなす","english":"to speak","ending_note":"su","short":{"present_aff":"はなす","present_neg":"はなさない","past_aff":"はなした","past_neg":"はなさなかった","te":"はなして","tai":"はなしたい","potential":"はなせる"},"long":{"present_aff":"はなします","present_neg":"はなしません","past_aff":"はなしました","past_neg":"はなしませんでした","te":"はなして","tai":"はなしたいです","potential":"はなせます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"貸す","reading":"かす","english":"to lend","ending_note":"su","short":{"present_aff":"かす","present_neg":"かさない","past_aff":"かした","past_neg":"かさなかった","te":"かして","tai":"かしたい","potential":"かせる"},"long":{"present_aff":"かします","present_neg":"かしません","past_aff":"かしました","past_neg":"かしませんでした","te":"かして","tai":"かしたいです","potential":"かせます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"入る","reading":"はいる","english":"to enter","ending_note":"ru→godan (looks ichidan)","short":{"present_aff":"はいる","present_neg":"はいらない","past_aff":"はいった","past_neg":"はいらなかった","te":"はいって","tai":"はいりたい","potential":"はいれる"},"long":{"present_aff":"はいります","present_neg":"はいりません","past_aff":"はいりました","past_neg":"はいりませんでした","te":"はいって","tai":"はいりたいです","potential":"はいれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"切る","reading":"きる","english":"to cut","ending_note":"ru→godan (looks ichidan)","short":{"present_aff":"きる","present_neg":"きらない","past_aff":"きった","past_neg":"きらなかった","te":"きって","tai":"きりたい","potential":"きれる"},"long":{"present_aff":"きります","present_neg":"きりません","past_aff":"きりました","past_neg":"きりませんでした","te":"きって","tai":"きりたいです","potential":"きれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"帰る","reading":"かえる","english":"to return home","ending_note":"ru→godan (looks ichidan)","short":{"present_aff":"かえる","present_neg":"かえらない","past_aff":"かえった","past_neg":"かえらなかった","te":"かえって","tai":"かえりたい","potential":"かえれる"},"long":{"present_aff":"かえります","present_neg":"かえりません","past_aff":"かえりました","past_neg":"かえりませんでした","te":"かえって","tai":"かえりたいです","potential":"かえれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"要る","reading":"いる","english":"to need","ending_note":"ru→godan (looks ichidan)","short":{"present_aff":"いる","present_neg":"いらない","past_aff":"いった","past_neg":"いらなかった","te":"いって","tai":"いりたい","potential":"いれる"},"long":{"present_aff":"いります","present_neg":"いりません","past_aff":"いりました","past_neg":"いりませんでした","te":"いって","tai":"いりたいです","potential":"いれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"走る","reading":"はしる","english":"to run","ending_note":"ru→godan (looks ichidan)","short":{"present_aff":"はしる","present_neg":"はしらない","past_aff":"はしった","past_neg":"はしらなかった","te":"はしって","tai":"はしりたい","potential":"はしれる"},"long":{"present_aff":"はしります","present_neg":"はしりません","past_aff":"はしりました","past_neg":"はしりませんでした","te":"はしって","tai":"はしりたいです","potential":"はしれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"I","kanji":"知る","reading":"しる","english":"to know","ending_note":"ru→godan (looks ichidan)","short":{"present_aff":"しる","present_neg":"しらない","past_aff":"しった","past_neg":"しらなかった","te":"しって","tai":"しりたい","potential":"しれる"},"long":{"present_aff":"しります","present_neg":"しりません","past_aff":"しりました","past_neg":"しりませんでした","te":"しって","tai":"しりたいです","potential":"しれます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"寝る","reading":"ねる","english":"to sleep","ending_note":"ru (ichidan)","short":{"present_aff":"ねる","present_neg":"ねない","past_aff":"ねた","past_neg":"ねなかった","te":"ねて","tai":"ねたい","potential":"ねられる"},"long":{"present_aff":"ねます","present_neg":"ねません","past_aff":"ねました","past_neg":"ねませんでした","te":"ねて","tai":"ねたいです","potential":"ねられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"食べる","reading":"たべる","english":"to eat","ending_note":"ru (ichidan)","short":{"present_aff":"たべる","present_neg":"たべない","past_aff":"たべた","past_neg":"たべなかった","te":"たべて","tai":"たべたい","potential":"たべられる"},"long":{"present_aff":"たべます","present_neg":"たべません","past_aff":"たべました","past_neg":"たべませんでした","te":"たべて","tai":"たべたいです","potential":"たべられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"見る","reading":"みる","english":"to see","ending_note":"ru (ichidan)","short":{"present_aff":"みる","present_neg":"みない","past_aff":"みた","past_neg":"みなかった","te":"みて","tai":"みたい","potential":"みられる"},"long":{"present_aff":"みます","present_neg":"みません","past_aff":"みました","past_neg":"みませんでした","te":"みて","tai":"みたいです","potential":"みられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"起きる","reading":"おきる","english":"to wake up","ending_note":"ru (ichidan)","short":{"present_aff":"おきる","present_neg":"おきない","past_aff":"おきた","past_neg":"おきなかった","te":"おきて","tai":"おきたい","potential":"おきられる"},"long":{"present_aff":"おきます","present_neg":"おきません","past_aff":"おきました","past_neg":"おきませんでした","te":"おきて","tai":"おきたいです","potential":"おきられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"着る","reading":"きる","english":"to wear","ending_note":"ru (ichidan)","short":{"present_aff":"きる","present_neg":"きない","past_aff":"きた","past_neg":"きなかった","te":"きて","tai":"きたい","potential":"きられる"},"long":{"present_aff":"きます","present_neg":"きません","past_aff":"きました","past_neg":"きませんでした","te":"きて","tai":"きたいです","potential":"きられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"浴びる","reading":"あびる","english":"to bathe / take a shower","ending_note":"ru (ichidan)","short":{"present_aff":"あびる","present_neg":"あびない","past_aff":"あびた","past_neg":"あびなかった","te":"あびて","tai":"あびたい","potential":"あびられる"},"long":{"present_aff":"あびます","present_neg":"あびません","past_aff":"あびました","past_neg":"あびませんでした","te":"あびて","tai":"あびたいです","potential":"あびられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"開ける","reading":"あける","english":"to open","ending_note":"ru (ichidan)","short":{"present_aff":"あける","present_neg":"あけない","past_aff":"あけた","past_neg":"あけなかった","te":"あけて","tai":"あけたい","potential":"あけられる"},"long":{"present_aff":"あけます","present_neg":"あけません","past_aff":"あけました","past_neg":"あけませんでした","te":"あけて","tai":"あけたいです","potential":"あけられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"閉める","reading":"しめる","english":"to close","ending_note":"ru (ichidan)","short":{"present_aff":"しめる","present_neg":"しめない","past_aff":"しめた","past_neg":"しめなかった","te":"しめて","tai":"しめたい","potential":"しめられる"},"long":{"present_aff":"しめます","present_neg":"しめません","past_aff":"しめました","past_neg":"しめませんでした","te":"しめて","tai":"しめたいです","potential":"しめられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"教える","reading":"おしえる","english":"to teach","ending_note":"ru (ichidan)","short":{"present_aff":"おしえる","present_neg":"おしえない","past_aff":"おしえた","past_neg":"おしえなかった","te":"おしえて","tai":"おしえたい","potential":"おしえられる"},"long":{"present_aff":"おしえます","present_neg":"おしえません","past_aff":"おしえました","past_neg":"おしえませんでした","te":"おしえて","tai":"おしえたいです","potential":"おしえられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"借りる","reading":"かりる","english":"to borrow","ending_note":"ru (ichidan)","short":{"present_aff":"かりる","present_neg":"かりない","past_aff":"かりた","past_neg":"かりなかった","te":"かりて","tai":"かりたい","potential":"かりられる"},"long":{"present_aff":"かります","present_neg":"かりません","past_aff":"かりました","past_neg":"かりませんでした","te":"かりて","tai":"かりたいです","potential":"かりられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"II","kanji":"降りる","reading":"おりる","english":"to get off","ending_note":"ru (ichidan)","short":{"present_aff":"おりる","present_neg":"おりない","past_aff":"おりた","past_neg":"おりなかった","te":"おりて","tai":"おりたい","potential":"おりられる"},"long":{"present_aff":"おります","present_neg":"おりません","past_aff":"おりました","past_neg":"おりませんでした","te":"おりて","tai":"おりたいです","potential":"おりられます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"III","kanji":"する","reading":"する","english":"to do","ending_note":"irregular","short":{"present_aff":"する","present_neg":"しない","past_aff":"した","past_neg":"しなかった","te":"して","tai":"したい","potential":"できる"},"long":{"present_aff":"します","present_neg":"しません","past_aff":"しました","past_neg":"しませんでした","te":"して","tai":"したいです","potential":"できます"}}'::jsonb),
  ('{"card_type":"verb_conjugation","group":"III","kanji":"来る","reading":"くる","english":"to come","ending_note":"irregular","short":{"present_aff":"くる","present_neg":"こない","past_aff":"きた","past_neg":"こなかった","te":"きて","tai":"きたい","potential":"こられる"},"long":{"present_aff":"きます","present_neg":"きません","past_aff":"きました","past_neg":"きませんでした","te":"きて","tai":"きたいです","potential":"こられます"}}'::jsonb)
) as v(fields);

-- =========================================================
-- Sanity check — should print one row with 34 cards.
-- =========================================================
select lv.order_index, lv.name, count(c.id) as cards
from module_levels lv
join modules m on m.id = lv.module_id
left join cards c on c.level_id = lv.id
where m.slug = 'conjugation'
  and lv.name = 'Verb Conjugation Reference'
group by lv.order_index, lv.name;
