-- =========================================================
-- Nihongo — N5 Nouns module seed  (generated)
-- Generated by scripts/generate_nouns_seed.mjs — DO NOT EDIT BY HAND.
-- Source: supabase/data/nouns_n5.json  (240 entries)
--
-- Structure: one module + 12 themed levels + 240 noun cards.
-- Card fields shape (for the noun_flashcard renderer):
--     { card_type: 'noun_flashcard', japanese, hiragana, english }
--
-- Idempotent — safe to re-run.
--   * Module: insert … on conflict (slug) do nothing
--   * Levels: insert only when a level with the same name is missing
--   * Cards:  insert only when the level currently holds zero cards
-- =========================================================

-- 1) Module
insert into modules (name, slug, description, type)
values (
  'N5 Nouns',
  'n5-nouns',
  'Essential JLPT N5 nouns, grouped by theme.',
  'quiz'
)
on conflict (slug) do nothing;

-- =========================================================
-- LEVEL 1 — People & Family (26 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'People & Family', 1, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'People & Family'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'People & Family'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('人', 'ひと', 'person'),
  ('男', 'おとこ', 'man'),
  ('女', 'おんな', 'woman'),
  ('男の人', 'おとこのひと', 'male, man'),
  ('女の人', 'おんなのひと', 'female, woman'),
  ('男の子', 'おとこのこ', 'boy'),
  ('女の子', 'おんなのこ', 'girl'),
  ('子供', 'こども', 'child'),
  ('大人', 'おとな', 'adult'),
  ('友達', 'ともだち', 'friend'),
  ('家族', 'かぞく', 'family'),
  ('父', 'ちち', 'father (own)'),
  ('母', 'はは', 'mother (own)'),
  ('お父さん', 'おとうさん', 'father (polite)'),
  ('お母さん', 'おかあさん', 'mother (polite)'),
  ('兄', 'あに', 'older brother (own)'),
  ('姉', 'あね', 'older sister (own)'),
  ('弟', 'おとうと', 'younger brother'),
  ('妹', 'いもうと', 'younger sister'),
  ('お兄さん', 'おにいさん', 'older brother (polite)'),
  ('お姉さん', 'おねえさん', 'older sister (polite)'),
  ('先生', 'せんせい', 'teacher'),
  ('学生', 'がくせい', 'student'),
  ('医者', 'いしゃ', 'doctor'),
  ('外国人', 'がいこくじん', 'foreigner'),
  ('名前', 'なまえ', 'name')
) as v(j, h, e);

-- =========================================================
-- LEVEL 2 — Food & Drink (24 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Food & Drink', 2, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Food & Drink'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Food & Drink'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('ご飯', 'ごはん', 'cooked rice, meal'),
  ('朝ご飯', 'あさごはん', 'breakfast'),
  ('昼ご飯', 'ひるごはん', 'lunch'),
  ('晩ご飯', 'ばんごはん', 'dinner'),
  ('食べ物', 'たべもの', 'food'),
  ('飲み物', 'のみもの', 'drink, beverage'),
  ('水', 'みず', 'water'),
  ('お茶', 'おちゃ', 'tea'),
  ('牛乳', 'ぎゅうにゅう', 'milk'),
  ('肉', 'にく', 'meat'),
  ('牛肉', 'ぎゅうにく', 'beef'),
  ('鳥肉', 'とりにく', 'chicken (meat)'),
  ('豚肉', 'ぶたにく', 'pork'),
  ('魚', 'さかな', 'fish'),
  ('野菜', 'やさい', 'vegetable'),
  ('果物', 'くだもの', 'fruit'),
  ('卵', 'たまご', 'egg'),
  ('パン', 'パン', 'bread'),
  ('塩', 'しお', 'salt'),
  ('砂糖', 'さとう', 'sugar'),
  ('料理', 'りょうり', 'cooking, dish'),
  ('お酒', 'おさけ', 'alcohol, sake'),
  ('コーヒー', 'コーヒー', 'coffee'),
  ('お菓子', 'おかし', 'sweets, snack')
) as v(j, h, e);

-- =========================================================
-- LEVEL 3 — Home & Everyday Objects (27 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Home & Everyday Objects', 3, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Home & Everyday Objects'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Home & Everyday Objects'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('本', 'ほん', 'book'),
  ('ノート', 'ノート', 'notebook'),
  ('ペン', 'ペン', 'pen'),
  ('鉛筆', 'えんぴつ', 'pencil'),
  ('紙', 'かみ', 'paper'),
  ('手紙', 'てがみ', 'letter'),
  ('辞書', 'じしょ', 'dictionary'),
  ('新聞', 'しんぶん', 'newspaper'),
  ('雑誌', 'ざっし', 'magazine'),
  ('写真', 'しゃしん', 'photograph'),
  ('時計', 'とけい', 'clock, watch'),
  ('傘', 'かさ', 'umbrella'),
  ('かばん', 'かばん', 'bag'),
  ('財布', 'さいふ', 'wallet'),
  ('かぎ', 'かぎ', 'key'),
  ('電話', 'でんわ', 'telephone'),
  ('テレビ', 'テレビ', 'television'),
  ('ラジオ', 'ラジオ', 'radio'),
  ('机', 'つくえ', 'desk'),
  ('椅子', 'いす', 'chair'),
  ('ドア', 'ドア', 'door'),
  ('窓', 'まど', 'window'),
  ('部屋', 'へや', 'room'),
  ('家', 'いえ', 'house, home'),
  ('テーブル', 'テーブル', 'table'),
  ('ベッド', 'ベッド', 'bed'),
  ('せっけん', 'せっけん', 'soap')
) as v(j, h, e);

-- =========================================================
-- LEVEL 4 — Places & Buildings (24 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Places & Buildings', 4, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Places & Buildings'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Places & Buildings'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('学校', 'がっこう', 'school'),
  ('大学', 'だいがく', 'university'),
  ('会社', 'かいしゃ', 'company'),
  ('銀行', 'ぎんこう', 'bank'),
  ('病院', 'びょういん', 'hospital'),
  ('図書館', 'としょかん', 'library'),
  ('郵便局', 'ゆうびんきょく', 'post office'),
  ('駅', 'えき', 'station'),
  ('店', 'みせ', 'shop, store'),
  ('きっさてん', 'きっさてん', 'café'),
  ('レストラン', 'レストラン', 'restaurant'),
  ('デパート', 'デパート', 'department store'),
  ('映画館', 'えいがかん', 'cinema'),
  ('公園', 'こうえん', 'park'),
  ('ホテル', 'ホテル', 'hotel'),
  ('空港', 'くうこう', 'airport'),
  ('町', 'まち', 'town'),
  ('国', 'くに', 'country'),
  ('道', 'みち', 'road, way'),
  ('トイレ', 'トイレ', 'toilet'),
  ('お手洗い', 'おてあらい', 'restroom'),
  ('台所', 'だいどころ', 'kitchen'),
  ('庭', 'にわ', 'garden'),
  ('プール', 'プール', 'swimming pool')
) as v(j, h, e);

-- =========================================================
-- LEVEL 5 — Time & Calendar (30 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Time & Calendar', 5, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Time & Calendar'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Time & Calendar'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('時間', 'じかん', 'time, hour'),
  ('今', 'いま', 'now'),
  ('朝', 'あさ', 'morning'),
  ('昼', 'ひる', 'noon, daytime'),
  ('夕方', 'ゆうがた', 'evening'),
  ('夜', 'よる', 'night'),
  ('晩', 'ばん', 'evening, night'),
  ('午前', 'ごぜん', 'morning, a.m.'),
  ('午後', 'ごご', 'afternoon, p.m.'),
  ('今日', 'きょう', 'today'),
  ('明日', 'あした', 'tomorrow'),
  ('昨日', 'きのう', 'yesterday'),
  ('毎日', 'まいにち', 'every day'),
  ('毎朝', 'まいあさ', 'every morning'),
  ('毎晩', 'まいばん', 'every night'),
  ('週', 'しゅう', 'week'),
  ('今週', 'こんしゅう', 'this week'),
  ('先週', 'せんしゅう', 'last week'),
  ('来週', 'らいしゅう', 'next week'),
  ('毎週', 'まいしゅう', 'every week'),
  ('月', 'つき', 'month, moon'),
  ('今月', 'こんげつ', 'this month'),
  ('先月', 'せんげつ', 'last month'),
  ('来月', 'らいげつ', 'next month'),
  ('年', 'とし', 'year'),
  ('今年', 'ことし', 'this year'),
  ('去年', 'きょねん', 'last year'),
  ('来年', 'らいねん', 'next year'),
  ('誕生日', 'たんじょうび', 'birthday'),
  ('曜日', 'ようび', 'day of the week')
) as v(j, h, e);

-- =========================================================
-- LEVEL 6 — Body & Health (15 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Body & Health', 6, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Body & Health'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Body & Health'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('体', 'からだ', 'body'),
  ('頭', 'あたま', 'head'),
  ('顔', 'かお', 'face'),
  ('目', 'め', 'eye'),
  ('耳', 'みみ', 'ear'),
  ('鼻', 'はな', 'nose'),
  ('口', 'くち', 'mouth'),
  ('は', 'は', 'tooth'),
  ('手', 'て', 'hand'),
  ('足', 'あし', 'foot, leg'),
  ('おなか', 'おなか', 'stomach, belly'),
  ('せ', 'せ', 'height, back'),
  ('病気', 'びょうき', 'illness'),
  ('薬', 'くすり', 'medicine'),
  ('元気', 'げんき', 'health, energy')
) as v(j, h, e);

-- =========================================================
-- LEVEL 7 — Transport & Travel (12 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Transport & Travel', 7, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Transport & Travel'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Transport & Travel'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('車', 'くるま', 'car'),
  ('電車', 'でんしゃ', 'train'),
  ('地下鉄', 'ちかてつ', 'subway'),
  ('自転車', 'じてんしゃ', 'bicycle'),
  ('自動車', 'じどうしゃ', 'automobile'),
  ('バス', 'バス', 'bus'),
  ('タクシー', 'タクシー', 'taxi'),
  ('飛行機', 'ひこうき', 'airplane'),
  ('船', 'ふね', 'ship, boat'),
  ('旅行', 'りょこう', 'travel, trip'),
  ('切符', 'きっぷ', 'ticket'),
  ('地図', 'ちず', 'map')
) as v(j, h, e);

-- =========================================================
-- LEVEL 8 — Nature & Weather (17 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Nature & Weather', 8, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Nature & Weather'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Nature & Weather'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('天気', 'てんき', 'weather'),
  ('雨', 'あめ', 'rain'),
  ('雪', 'ゆき', 'snow'),
  ('風', 'かぜ', 'wind'),
  ('空', 'そら', 'sky'),
  ('海', 'うみ', 'sea'),
  ('山', 'やま', 'mountain'),
  ('川', 'かわ', 'river'),
  ('木', 'き', 'tree, wood'),
  ('花', 'はな', 'flower'),
  ('池', 'いけ', 'pond'),
  ('石', 'いし', 'stone'),
  ('火', 'ひ', 'fire'),
  ('動物', 'どうぶつ', 'animal'),
  ('犬', 'いぬ', 'dog'),
  ('猫', 'ねこ', 'cat'),
  ('鳥', 'とり', 'bird')
) as v(j, h, e);

-- =========================================================
-- LEVEL 9 — Clothing & Colors (20 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Clothing & Colors', 9, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Clothing & Colors'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Clothing & Colors'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('服', 'ふく', 'clothes'),
  ('洋服', 'ようふく', 'Western clothes'),
  ('シャツ', 'シャツ', 'shirt'),
  ('Tシャツ', 'ティーシャツ', 'T-shirt'),
  ('上着', 'うわぎ', 'jacket, coat'),
  ('コート', 'コート', 'coat'),
  ('ズボン', 'ズボン', 'trousers'),
  ('スカート', 'スカート', 'skirt'),
  ('帽子', 'ぼうし', 'hat, cap'),
  ('靴', 'くつ', 'shoes'),
  ('靴下', 'くつした', 'socks'),
  ('めがね', 'めがね', 'glasses'),
  ('色', 'いろ', 'color'),
  ('白', 'しろ', 'white'),
  ('黒', 'くろ', 'black'),
  ('赤', 'あか', 'red'),
  ('青', 'あお', 'blue'),
  ('緑', 'みどり', 'green'),
  ('黄色', 'きいろ', 'yellow'),
  ('茶色', 'ちゃいろ', 'brown')
) as v(j, h, e);

-- =========================================================
-- LEVEL 10 — School, City & Work (20 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'School, City & Work', 10, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'School, City & Work'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'School, City & Work'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('教室', 'きょうしつ', 'classroom'),
  ('授業', 'じゅぎょう', 'class, lesson'),
  ('宿題', 'しゅくだい', 'homework'),
  ('テスト', 'テスト', 'test'),
  ('問題', 'もんだい', 'problem, question'),
  ('質問', 'しつもん', 'question'),
  ('言葉', 'ことば', 'word, language'),
  ('英語', 'えいご', 'English (language)'),
  ('日本語', 'にほんご', 'Japanese (language)'),
  ('仕事', 'しごと', 'work, job'),
  ('会議', 'かいぎ', 'meeting'),
  ('お金', 'おかね', 'money'),
  ('円', 'えん', 'yen'),
  ('番号', 'ばんごう', 'number'),
  ('電気', 'でんき', 'electricity, light'),
  ('音楽', 'おんがく', 'music'),
  ('映画', 'えいが', 'movie'),
  ('絵', 'え', 'picture, drawing'),
  ('歌', 'うた', 'song'),
  ('スポーツ', 'スポーツ', 'sport')
) as v(j, h, e);

-- =========================================================
-- LEVEL 11 — Positions & Directions (15 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Positions & Directions', 11, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Positions & Directions'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Positions & Directions'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('上', 'うえ', 'up, above, on'),
  ('下', 'した', 'down, below, under'),
  ('中', 'なか', 'inside, middle'),
  ('外', 'そと', 'outside'),
  ('前', 'まえ', 'front, before'),
  ('後ろ', 'うしろ', 'behind, back'),
  ('右', 'みぎ', 'right'),
  ('左', 'ひだり', 'left'),
  ('隣', 'となり', 'next to, neighbor'),
  ('側', 'そば', 'beside, near'),
  ('近く', 'ちかく', 'nearby'),
  ('東', 'ひがし', 'east'),
  ('西', 'にし', 'west'),
  ('南', 'みなみ', 'south'),
  ('北', 'きた', 'north')
) as v(j, h, e);

-- =========================================================
-- LEVEL 12 — Misc & Abstract (10 nouns)
-- =========================================================
with m as (select id from modules where slug = 'n5-nouns')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Misc & Abstract', 12, 'hiragana' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Misc & Abstract'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'n5-nouns' and lv.name = 'Misc & Abstract'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, jsonb_build_object(
  'card_type', 'noun_flashcard',
  'japanese', j,
  'hiragana', h,
  'english', e
)
from do_seed ds
cross join (values
  ('物', 'もの', 'thing (object)'),
  ('事', 'こと', 'thing (abstract), matter'),
  ('話', 'はなし', 'talk, story'),
  ('所', 'ところ', 'place'),
  ('方', 'かた', 'way, direction, person (polite)'),
  ('意味', 'いみ', 'meaning'),
  ('趣味', 'しゅみ', 'hobby'),
  ('文', 'ぶん', 'sentence'),
  ('字', 'じ', 'character, letter'),
  ('ページ', 'ページ', 'page')
) as v(j, h, e);

-- =========================================================
-- Sanity check — should print 12 rows with the expected counts.
-- =========================================================
select lv.order_index, lv.name, count(c.id) as cards
from module_levels lv
join modules m on m.id = lv.module_id
left join cards c on c.level_id = lv.id
where m.slug = 'n5-nouns'
group by lv.order_index, lv.name
order by lv.order_index;
