#!/usr/bin/env node
// Reads supabase/data/adjectives.json and writes
// supabase/seed_adjectives.sql. Mirrors generate_verbs_seed.mjs.
//
//   node scripts/generate_adjectives_seed.mjs
//
// Idempotent SQL: level skipped if present, cards skipped if level
// already has any. Re-running after editing the JSON requires
// emptying the level first.

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const INPUT = resolve(root, "supabase/data/adjectives.json");
const OUTPUT = resolve(root, "supabase/seed_adjectives.sql");

// Keys persisted per card (we intentionally drop `definition_fr`).
const SQL_FIELDS = [
  "kanji",
  "hiragana",
  "long_form",
  "short_form",
  "definition_en",
  "opposite",
];

function sqlString(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function cardJson(adj) {
  const fields = { card_type: "adjective_flashcard" };
  for (const k of SQL_FIELDS) fields[k] = adj[k] ?? "";
  return JSON.stringify(fields);
}

const raw = await readFile(INPUT, "utf8");
const adjectives = JSON.parse(raw);

const cardsValues = adjectives
  .map((a) => `  (${sqlString(cardJson(a))})`)
  .join(",\n");

const sql = `-- =========================================================
-- Nihongo — Adjectives flashcards seed
-- Generated by scripts/generate_adjectives_seed.mjs from
--   supabase/data/adjectives.json (${adjectives.length} adjectives).
-- Adds one level "Adjectives" to the vocabulary module.
-- Idempotent: re-running is a no-op once the level is populated.
-- =========================================================

-- ─── Level: Adjectives (${adjectives.length} cards) ─────────────────
with m as (select id from modules where slug = 'vocabulary')
insert into module_levels (module_id, name, order_index, script)
select m.id, 'Adjectives', 102, 'none' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = 'Adjectives'
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'vocabulary' and lv.name = 'Adjectives'
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, fld::jsonb from do_seed ds
cross join (values
${cardsValues}
) as v(fld);

-- Sanity check
select lv.order_index, lv.name, count(c.id) as cards
from module_levels lv
join modules m on m.id = lv.module_id
left join cards c on c.level_id = lv.id
where m.slug = 'vocabulary' and lv.name = 'Adjectives'
group by lv.order_index, lv.name;
`;

await writeFile(OUTPUT, sql, "utf8");

console.log(`Wrote ${OUTPUT}`);
console.log(`  Adjectives: ${adjectives.length}`);
