#!/usr/bin/env node
// Reads supabase/data/verbs.json and writes supabase/seed_verbs.sql.
//
//   node scripts/generate_verbs_seed.mjs
//
// The generated SQL is idempotent: creating the levels skips when they
// exist, and the card inserts only fire when the level is currently
// empty. Re-running after editing the JSON requires emptying the level
// first (or using a different level name).

import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const INPUT = resolve(root, "supabase/data/verbs.json");
const OUTPUT = resolve(root, "supabase/seed_verbs.sql");

const SQL_FIELDS = [
  "group",
  "dictionary_form",
  "te_form",
  "ta_form",
  "nai_form",
  "masu_form",
  "potential_form",
  "translation_en",
];

function sqlString(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function cardJson(verb) {
  const fields = { card_type: "verb_flashcard" };
  for (const k of SQL_FIELDS) fields[k] = verb[k] ?? "";
  return JSON.stringify(fields);
}

function levelBlock(levelName, orderIndex, verbs) {
  const cardsValues = verbs
    .map((v) => `  (${sqlString(cardJson(v))})`)
    .join(",\n");

  return `
-- ─── Level: ${levelName} (${verbs.length} cards) ─────────────────────
with m as (select id from modules where slug = 'vocabulary')
insert into module_levels (module_id, name, order_index, script)
select m.id, ${sqlString(levelName)}, ${orderIndex}, 'none' from m
where not exists (
  select 1 from module_levels lv
  where lv.module_id = (select id from m) and lv.name = ${sqlString(levelName)}
);

with lv as (
  select lv.id from module_levels lv
  join modules m on m.id = lv.module_id
  where m.slug = 'vocabulary' and lv.name = ${sqlString(levelName)}
),
do_seed as (
  select id from lv where not exists (select 1 from cards c where c.level_id = lv.id)
)
insert into cards (level_id, fields)
select ds.id, fld::jsonb from do_seed ds
cross join (values
${cardsValues}
) as v(fld);
`;
}

const raw = await readFile(INPUT, "utf8");
const verbs = JSON.parse(raw);

const sng = verbs.filter((v) => v.SNG_list === "yes");
const extra = verbs.filter((v) => v.SNG_list === "no");

const header = `-- =========================================================
-- Nihongo — Verbs flashcards seed
-- Generated by scripts/generate_verbs_seed.mjs from
--   supabase/data/verbs.json (${verbs.length} verbs total).
-- Adds two levels to the "vocabulary" module and seeds them.
-- Idempotent: re-running is a no-op once the levels are populated.
-- =========================================================
`;

const sql =
  header +
  levelBlock("Verbs — SNG List", 100, sng) +
  levelBlock("Verbs — Extra", 101, extra) +
  `
-- Sanity check
select lv.order_index, lv.name, count(c.id) as cards
from module_levels lv
join modules m on m.id = lv.module_id
left join cards c on c.level_id = lv.id
where m.slug = 'vocabulary'
  and lv.name in ('Verbs — SNG List', 'Verbs — Extra')
group by lv.order_index, lv.name
order by lv.order_index;
`;

await writeFile(OUTPUT, sql, "utf8");

console.log(`Wrote ${OUTPUT}`);
console.log(`  SNG List: ${sng.length} cards`);
console.log(`  Extra:    ${extra.length} cards`);
console.log(`  Total:    ${verbs.length} cards`);
